### ISSUE TITLE
rasterio vs python gdal

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#11]
There are currently two major opens source packages for handling rasterdata. Both are based on [GDAL](http://gdal.org/) and both offer an easy way to extract data to numpy as used in our calculations: 
 * [python GDAL](https://pypi.python.org/pypi/GDAL): based on the GDAL C++ api (swig generated). Supports all the functionality of GDAL. Feature rich but code is a bit harder to understand.
 * [rasterio](https://github.com/mapbox/rasterio) : has a 'pythonic' interface usually resulting in less code and better readability

Since we will not be using any fancy features, I think rasterio is a better option for us. 
I've checked and both are available on windows (conda forge). 

Note that it is not considered a good idea to use both together: [mutual incompatibilities](https://mapbox.github.io/rasterio/switch.html#mutual-incompatibilities).

@stijnvanhoey : is there a specific reason you opted for the gdal library rather than rasterio for your preliminary investigations (https://github.com/inbo/niche_vlaanderen/issues/1)

**Comment by stijnvanhoey** [comment]
I indeed do agree that `rasterio` is more Pythonic compared to the swig generated gdal library. The cross-platform availability is a key-point indeed, but covered for both. I am aware of the mutual incompatibilities. 

The reason that I opted for GDAL is just the fact that I was already familiar with the GDAL package. Moreover, as it was used just for reading in files, I do think the GDAL library was sufficiently readable. 

I would be ok to opt for the rasterio package, what do you think is most appropriate for handling raster data @jeroendereu?

**Comment by jeroendereu** [comment]
In my recent work, I opted for GDAL, for two reasons:
- `python GDAL` answered my needs: conversion between different raster fileformats (e.g. JP2 to GeoTIFF) coordinate transformations, mosaicing and clipping of rasters, etc..
- `Rasterio` was incompatible with another package I intended to use.

I am using `numpy` to perform raster calculations.

**Comment by johanvdw** [comment]
Which package was incompatible?

**Comment by jeroendereu** [comment]
I had problems with basemap, but in the end I used neither of those packages.

**Comment by stijnvanhoey** [comment]
Maybe to add to the discussion, if the main purpose of the library is to read GIS data, reprojection, visualisation and conversion towards arrays, the [cartopy library](https://github.com/SciTools/cartopy) could be a valid option in combination with pure GDAL (instead of rasterio)?

I see that the requirements are in function of the [functionalities](https://github.com/SciTools/cartopy/tree/master/requirements), but as the plotting is already depending on GDAL, it could work to combine these two to fulfill the requirements

Cartopy provides high-level methods for [WMS and WMTS](http://scitools.org.uk/cartopy/docs/latest/cartopy/io/ogc_clients.html#module-cartopy.io.ogc_clients) as well.

**Comment by johanvdw** [comment]
I have chosen `rasterio` for now.

Dependency management is somewhat easier in rasterio as python-gdal relies on a specific version of gdal. Eg when gdal was updated to 2.2.2 earlier this week, the travis build failed because the repository does not yet contain that version. I could fix a version in requirements.txt, but that would than also be asked by other users.
