### ISSUE TITLE
Add option to use only one value instead of complete grid

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#15]
Browsing through the examples, I noticed that sometimes grids get only a constant value.
eg

- rainwater lense: 0
- fertilizer: 0
- conductivity: 501
- deposition: 30

We should add an option to assign a fixed number rather than having to create a grid for this.

**Comment by cecileherr** [comment]
Yes, we often create a grid with a fake unique value if we want to use the same unique category for a given parameter for the whole study area. 

Nice to add an option to use a unique value instead of making a grid, 
It could even be more user-friendly to select a category instead of typing a value (e.g. for conductivity: grondwater with high mineral content instead of 501) but with a downside: the categories are then fixed in the code (they are now in the conversion table and could be easily adapted if needed)

**Comment by johanvdw** [comment]
@cecileherr: Can we assume that soil_code is always a grid? And/or that MHW/MLW/MSW are always grids?

**Comment by cecileherr** [comment]
Soil_code is originally a shapefile (that we convert into a grid using the groundwater levels grids as example for the extent and cell size) and MHW/MLW/MSW are always grids.
