### ISSUE TITLE
Validation: what happens when extent shp is larger than raster

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#307]
niche_vlaanderen version: dev 1.1
Python version: 3
Operating System: Win

I tested the validation module with a vegetation shapefile (bwk) with a (slightly) larger extent than the input rasters of the model and I think there might be a problem in this case.

- With the calculation of `polygon_count`:
My guess is that `polygon_count ` is based on the full extent of the shp while it should be based on a smaller extent, that is: the extent overlapping with the input rasters. 

- With the calculation of the scores
When I use the same bwk in 2 examples, but one with a version clipped to the extent of the rasters and the other one with a larger extent (and polygons extending outside the extent of the rasters), I get unexpectedly very different validation scores. Are zones with NoData (= outside extent niche model)  considered as zones with no potentialities instead of NoData?

Could you check these points please?

Example based on Brasschaat + shp in attachment (you will need to change the paths for the bwk though)
[bwk_fake_brasschaat.zip](https://github.com/inbo/niche_vlaanderen/files/10075606/bwk_fake_brasschaat.zip)

```
simplebr = nv.Niche()
simplebr.run_config_file(path_nv + "tests/data/bwk/niche_brasschaat/simple.yaml")

from niche_vlaanderen.bwk_overlay import NicheOverlay

# with extent = same as rasters
no_simplebr_fkok = NicheOverlay(niche=simplebr, map= path_ch + "testcase_extra/brasschaat/bwk/bwk_fake_extentok.shp")
no_simplebr_fkok.overlay()

no_simplebr_fkok.summary

# with extent = larger than rasters
no_simplebr_fkl = NicheOverlay(niche=simplebr, map= path_ch + "testcase_extra/brasschaat/bwk/bwk_fake_extentlarger.shp")
no_simplebr_fkl.overlay()

no_simplebr_fkl.summary
```

**Comment by johanvdw** [comment]
![image](https://user-images.githubusercontent.com/868434/212075623-43ffbe27-77a9-44e0-9b76-78ee0d641a88.png)

In this case: the second polygon (half covering the niche model):
the area of the polygon is 600 ha, but the overlap with the map is only 70% so the area used for area_effective  should be reduced. 
In the last polygon (outside the niche domain) effective area should become 0.

* area_pot and area_nonpot should be unaffected (based on zonal statistics)
* area_pot_perc is unaffected as only based on area_pot and area_nonpot
* area_nonpot_optimistc and area_pot_perc_optimistic will be adjusted because the effective area changes.

**Comment by johanvdw** [comment]
Updated calculation:

![image](https://user-images.githubusercontent.com/868434/212683932-8dc055e4-fd0e-442a-be53-ceb0cd780baf.png)

**Comment by cecileherr** [comment]
Still using the same example as above I get a strange result for

**Comment by cecileherr** [comment]
just as a reference in the future: this a better version of test shapefiles
[bwk_fake_extentok_mini.zip](https://github.com/inbo/niche_vlaanderen/files/10556743/bwk_fake_extentok_mini.zip)
