### ISSUE TITLE
table attribute not available

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#58]
In the current documentation, a table attribute is available to the class. 

![image](https://user-images.githubusercontent.com/754862/32896194-acec0e8a-cae2-11e7-96f0-dc31ed983cd3.png)

However, when running the model, this attribute is not available... The `occurrence` is available, but this is not documented and provided as a `dict`.

**Comment by johanvdw** [comment]
The table attribute was added in https://github.com/inbo/niche_vlaanderen/commit/4e0bd41d49688db8185f0b8e7eaabe9f97dca329

Are you using the version from pypi?

**Comment by stijnvanhoey** [comment]
yup

**Comment by johanvdw** [comment]
This was caused because the documentation was ahead of the released version on pypi. I have now released another version. After [upgrading the installation](https://inbo.github.io/niche_vlaanderen/installation.html#upgrading-the-installation), you should be able to use the table function as intended
